package app.blade.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFF8ECFF4)
val onPrimaryDark = Color(0xFF00344F)
val primaryContainerDark = Color(0xFF004C70)
val onPrimaryContainerDark = Color(0xFFC4E7FF)

val secondaryDark = Color(0xFFB3CAD8)
val onSecondaryDark = Color(0xFF1D333E)
val secondaryContainerDark = Color(0xFF344955)
val onSecondaryContainerDark = Color(0xFFCFE6F4)

val tertiaryDark = Color(0xFFCBBFE8)
val onTertiaryDark = Color(0xFF332B4B)
val tertiaryContainerDark = Color(0xFF4A4163)
val onTertiaryContainerDark = Color(0xFFE8DBFF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDEE3E8)
val surfaceDark = Color(0xFF0F1417)
val onSurfaceDark = Color(0xFFDEE3E8)
val surfaceVariantDark = Color(0xFF3D4850)
val onSurfaceVariantDark = Color(0xFFBCC8D0)
val outlineDark = Color(0xFF869299)
val outlineVariantDark = Color(0xFF3D4850)
val surfaceContainerLowestDark = Color(0xFF090E11)
val surfaceContainerLowDark = Color(0xFF171D20)
val surfaceContainerDark = Color(0xFF1B2124)
val surfaceContainerHighDark = Color(0xFF252C2F)
val surfaceContainerHighestDark = Color(0xFF30373A)

val primaryLight = Color(0xFF006696)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC4E7FF)
val onPrimaryContainerLight = Color(0xFF001E30)

val secondaryLight = Color(0xFF4C616D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E6F4)
val onSecondaryContainerLight = Color(0xFF071E28)

val tertiaryLight = Color(0xFF61597E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE8DBFF)
val onTertiaryContainerLight = Color(0xFF1D1737)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFF6FAFD)
val onBackgroundLight = Color(0xFF171D20)
val surfaceLight = Color(0xFFF6FAFD)
val onSurfaceLight = Color(0xFF171D20)
val surfaceVariantLight = Color(0xFFD8E4EE)
val onSurfaceVariantLight = Color(0xFF3D4850)
val outlineLight = Color(0xFF6E7881)
val outlineVariantLight = Color(0xFFBCC8D0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F7)
val surfaceContainerLight = Color(0xFFE9EEF2)
val surfaceContainerHighLight = Color(0xFFE4E9EC)
val surfaceContainerHighestLight = Color(0xFFDEE3E8)
